name: Readability build and Release

on:  
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34.x

      - name: Deno compile
        run: |
          deno compile --unstable --allow-read --allow-write --allow-net --allow-env --output=readability readability.js

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: readability
          path: ./readability

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: readability

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{  github.ref_name }}-${{ steps.date.outputs.date }}
        run: |
          gh release create "$tag" readability \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
